config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'categories/index'
  # get 'categories/show'
  resources :categories, only: %i[index show]
  resources :pages, except: [:show]
  resources :cart, only: %i[create destroy]
  get "/cart", to: "cart#show", as: "show_cart"

  get "pages/:permalink" => "pages#permalink", as: "permalink" # this is equivalent to permalink_path
  # get 'products/index'
  # get 'products/show'
  # get 'manufacturers/index'
  # get 'manufacturers/show'
  resources :products, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :manufacturers, only: %i[index show]
  root to: "products#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, uniqueness: true

  def self.products_in_category
    self.select("categories.*")
        .select("COUNT(categories.id) as category_count")
        .left_joins(:products)
        .group("categories.id")
        .order("category_count DESC")
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products
  validates :name, presence: true

  def self.ordered_by_products
    self.select("manufacturers.*")
        .select("COUNT(manufacturers.id) as product_count")
        .left_joins(:products)
        .group("manufacturers.id")
        .order("product_count DESC")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :users
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :manufacturer
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :order_items

  validates :name, :price, :description, presence: true
  validates :price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    # Adds params[:id] to cart
    # id relates to the product you click add to cart on
    # when creating a new cart item, its done when a user clicks a new item to add
    # using the id they clicked, we create a cart item
    # the logger will show in the rails server.. super useful for debugging!!
    logger.debug("Adding #{params[:id]} to cart.")
    # all query params come in as strings, so you need to convert to integer
    # to put it into the id array it had to be an integer
    id = params[:id].to_i
    # now the shopping cart array contains the id of the new product
    session[:shopping_cart] << id # pushes id onto the end of the array/list

    # Get the product from the id that the user selected
    # get the name of that product and add it to the flash notification
    # flash notification is used in application.html.erb
    product = Product.find(id)
    # show user that product was added
    flash[:notice] = "➕ #{product.name} added to cart."

    redirect_to root_path
  end

  # DELETE /cart/:id
  def destroy
    # removes params[:id] from cart
    logger.debug("Removing #{params[:id]} from cart.")
    id = params[:id].to_i
    # removes that product id from the array of product ids
    session[:shopping_cart].delete(id)
    product = Product.find(id)
    flash[:notice] = " - #{product.name} removed from cart."
    redirect_to root_path
  end

  def show
    # @cart = Cart.find(params[:id])
    logger.debug("Items in cart:" + session[:shopping_cart].inspect)
    @items_in_cart = session[:shopping_cart].count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[edit update destroy]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html do
          redirect_to permalink_path(@page.permalink), notice: "Page was successfully created."
        end
        format.json { render :show, status: :created, location: permalink_path(@page.permalink) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html do
          redirect_to permalink_path(@page.permalink), notice: "Page was successfully updated."
        end
        format.json { render :show, status: :ok, location: permalink_path(@page.permalink) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    # @products = Product.includes(:manufacturer).all
    @products = Product.page(params[:page])
    @manufacturers = Manufacturer.ordered_by_products.limit(15)
  end

  def show
    @product = Product.find(params[:id])
  end

  def about
    # just setting the path, can leave this empty for now
  end

  def search
    @products = if !params[:id].empty?
                  Product.where("manufacturer_id = #{params[:id]}").where(
                    "name OR description LIKE ?", "%#{params[:search_term]}%"
                  )

                else
                  Product.where("name OR description LIKE ?", "%#{params[:search_term]}%")
                end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<% name = current_user.present? ? current_user.email : ' '%>
<% if user_signed_in? %>
<h3>Welcome to the shop <%= name %></h3>
<% end %>
<aside>
  <div class="container">
    <div class="row justify-content-center">
       <% if product.image.present? %>
      <p><%= image_tag product.image.variant(resize_to_limit: [285, 285]).processed  %></p>
    <% end %>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <p class="h3">
        <% if show_link %>
          <%= link_to product.name, product %>
        <% else %>
          <%= product.name %>
        <% end %>
      </p>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <p class="h5">Price: <%= product.price %></p>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
     <% if single_page %>
        <p class="h6"><%= product.description %></p>
        <p class="h6">----Quantity in stock:<%= product.quantity %></p>
      <% else %>
        <p>Click on the product name to view description and quantity in stock</p>
      <% end %>
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
       <% if cart.include?(product) %>
      <%= button_to cart_path(product), method: :delete do %>
        Remove From Cart
      <% end %>
    <% else %>
      <%= form_with  url: cart_index_path, method: :post do %>
      <%# this line below says id equals id of the product, hidden rails magic to add to cart %>
        <%= hidden_field_tag(:id, product.id) %>
        <%= button_tag 'Add to Cart' %>
      <% end %>
    <% end %>
    </div>
  </div>
</aside>

app/views/products/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h2 class= "display-2">Products</h2>
  </div>
</div>

<%= render partial: @products, locals: {show_link: true, single_page: false } %>
<%= paginate @products %>

app/views/products/search.html.erb
<p class="mb-5">
  Found <%= pluralize(@products.count, 'Product') %> when searching for: <%= params[:keywords] %>
</p>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product %></li>
  <% end %>
</ul>

app/views/products/show.html.erb
<% content_for(:html_title) { @product.name }%>



<%= render partial: 'product', object: @product, locals: {show_link: false, single_page: true} %>