config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'categories/index'
  # get 'categories/show'
  resources :categories, only: %i[index show]
  resources :pages, except: [:show]
  resources :cart, only: %i[create destroy]
  get "/cart", to: "cart#show", as: "show_cart"

  get "pages/:permalink" => "pages#permalink", as: "permalink" # this is equivalent to permalink_path
  # get 'products/index'
  # get 'products/show'
  # get 'manufacturers/index'
  # get 'manufacturers/show'
  resources :products, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :manufacturers, only: %i[index show]
  root to: "products#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
  validates :name, presence: true, uniqueness: true

  def self.products_in_category
    self.select("categories.*")
        .select("COUNT(categories.id) as category_count")
        .left_joins(:products)
        .group("categories.id")
        .order("category_count DESC")
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products
  validates :name, presence: true

  def self.ordered_by_products
    self.select("manufacturers.*")
        .select("COUNT(manufacturers.id) as product_count")
        .left_joins(:products)
        .group("manufacturers.id")
        .order("product_count DESC")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  belongs_to :users
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  belongs_to :manufacturer
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :order_items

  validates :name, :price, :description, presence: true
  validates :price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    # Adds params[:id] to cart
    # id relates to the product you click add to cart on
    # when creating a new cart item, its done when a user clicks a new item to add
    # using the id they clicked, we create a cart item
    # the logger will show in the rails server.. super useful for debugging!!
    logger.debug("Adding #{params[:id]} to cart.")
    # all query params come in as strings, so you need to convert to integer
    # to put it into the id array it had to be an integer
    id = params[:id].to_i
    # now the shopping cart array contains the id of the new product
    session[:shopping_cart] << id # pushes id onto the end of the array/list

    # Get the product from the id that the user selected
    # get the name of that product and add it to the flash notification
    # flash notification is used in application.html.erb
    product = Product.find(id)
    # show user that product was added
    flash[:notice] = "➕ #{product.name} added to cart."

    redirect_to root_path
  end

  # DELETE /cart/:id
  def destroy
    # removes params[:id] from cart
    logger.debug("Removing #{params[:id]} from cart.")
    id = params[:id].to_i
    # removes that product id from the array of product ids
    session[:shopping_cart].delete(id)
    product = Product.find(id)
    flash[:notice] = " - #{product.name} removed from cart."
    redirect_to root_path
  end

  def show
    # @cart = Cart.find(params[:id])
    logger.debug("Items in cart:" + session[:shopping_cart].inspect)
    @items_in_cart = session[:shopping_cart].count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <p><em>Parbjot ECommerce</em></p>
  <ul class="mt-5">
    <li><%= link_to "Products", root_path %></li>
    <li><%= link_to "Product Manufacturers", manufacturers_path %></li>
    <li><%= link_to "Product Categories", categories_path %></li>
    <% cms_pages.each do | page | %>
      <li><%= link_to page.title, permalink_path(page.permalink) %></li>
    <% end %>
  </ul>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Home', root_path, class: 'nav-link' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <li class="nav-item">
           <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Suppliers', manufacturers_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " - " if content_for?(:html_title) %>Products</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <%= render 'common/navbar' %>

  <div class="container">
    <div class="row justify-content-center">
      <h2 class="display-2"><%= link_to "Kitchen Ecommerce", root_path %></h2>
    </div>
  </div>
    <body>
  <%= form_with(url: search_products_path, local: true, method: "get", class: 'd-flex') do %>
          <div class="field is-grouped mb-5">
            <div class="control is-expanded">
              <%= text_field_tag(:search_term, nil, class: 'form-control', placeholder: 'Search Products') %>
              <%= select_tag(:id, options_for_select(@c),{ :include_blank => "Select Category"}) %>
            </div>
            <div class="control">
              <%= submit_tag("Search", class: "btn btn-warning") %>
            </div>
          </div>
        <% end %>
    <nav>
        <%= link_to image_tag("add-to-basket.png", width:60), show_cart_path %>
        <ul>
          <li>
            Cart

          </li>
        </ul>
      </nav>
<% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>
  <%= yield %>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
        <details>
        <summary>
            Cart
            <% if cart.present? %>
              <sup><%= cart.size %></sup>
            <% end %>
        </summary>
        <% if cart.present? %>
          <ul>
            <% cart.each do |product| %>
              <li>
                <%= product.name %> <%= link_to '❌', cart_path(product), method: :delete %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No items in your cart.</p>
        <% end %>
      </details>
    <%= render partial: 'common/footer' %>



</section>
 <style>
body {
  background-image: url('https://i2.wp.com/offcon.net/wp-content/uploads/2020/04/0-3357_3840x2160-silver-blur-background-wallpaper-wallpaper-high-resolution-scaled.jpg?fit=2560%2C1440&ssl=1');
}
</style>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :content, class: 'label' %>
    <%= form.text_area :content, class: 'textarea' %>
  </div>

  <div class="field">
    <%= form.label :permalink, class: 'label' %>
    <%= form.text_field :permalink, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2 class="title is-4">Editing Page</h2>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4">Pages</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page, class: 'button is-info' %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'button is-warning' %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path, class: 'button is-primary' %>

app/views/pages/new.html.erb
<h2 class="title is-4">New Page</h2>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>